### ISSUE TITLE
[bug] Taglist does not start or takes a long time to start

### ISSUE THREAD

**Issue by poiuedws** [ilovecookieee/Glorious-Dotfiles#15]
https://i.imgur.com/C9a80Hf.jpg

for some reason closing and opening the system tray makes the taglist show up,
would appricate a fix.

**Comment by ilovecookieee** [comment]
Taglist is loaded on startup. The problem is that the wibox panel doesn't show it or refresh the content when the widget is passed on to the `decorateWidget(widget)` function. I tried fixing this long ago but never came up with the solution. Quick fix to refresh the wibox is to switch tag or open a client. But I will look into this later.

**Comment by poiuedws** [comment]
Would there be a way to force refresh it after startup is completed?

**Comment by ilovecookieee** [comment]
I don't have an exact solution right now, tbh. The only idea I have is to switch tags on start-up to refresh the wibox but it's a bit hackish so I don't recommend it lol

**Comment by ilovecookieee** [comment]
Hey, I tried updating my AwesomeWM. https://github.com/awesomeWM/awesome/pull/2952 this should fix the problem. I tested it and the wibox panel shows the taglist now on startup.

**Comment by poiuedws** [comment]
Can confirm, issue closed
